services:
  mongodb:
    image: mongo:6
    container_name: skillswap-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: skillswap-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/skillswap
    depends_on:
      - mongodb

  frontend:
    build:
      context: C:\Users\salma\Downloads\skillswap\backoffice
      dockerfile: Dockerfile.frontend
    container_name: skillswap-frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mongo-data: